const fs = require("fs");

// Source of truth: the enriched exercises JSON (generated by `npm run build:exercises`)
const exercises = require("./public/exercises/exercises.json");
const exerciseIds = exercises.map(e => e.id);

console.log("Total enriched exercises:", exerciseIds.length);

// Verify translations match enriched exercise IDs
const caTrans = JSON.parse(fs.readFileSync("src/i18n/locales/ca/exercises.json", "utf8"));
const esTrans = JSON.parse(fs.readFileSync("src/i18n/locales/es/exercises.json", "utf8"));
const enTrans = JSON.parse(fs.readFileSync("src/i18n/locales/en/exercises.json", "utf8"));
const caKeys = new Set(Object.keys(caTrans));
const esKeys = new Set(Object.keys(esTrans));
const enKeys = new Set(Object.keys(enTrans));

const missingCa = exerciseIds.filter(id => !caKeys.has(id));
const missingEs = exerciseIds.filter(id => !esKeys.has(id));
const missingEn = exerciseIds.filter(id => !enKeys.has(id));

console.log("Missing CA translations:", missingCa.length ? missingCa : "NONE");
console.log("Missing ES translations:", missingEs.length ? missingEs : "NONE");
console.log("Missing EN translations:", missingEn.length ? missingEn : "NONE");
console.log("CA keys:", caKeys.size, "ES keys:", esKeys.size, "EN keys:", enKeys.size);

const musclesCa = JSON.parse(fs.readFileSync("src/i18n/locales/ca/muscles.json", "utf8"));
const musclesEs = JSON.parse(fs.readFileSync("src/i18n/locales/es/muscles.json", "utf8"));
const musclesEn = JSON.parse(fs.readFileSync("src/i18n/locales/en/muscles.json", "utf8"));
console.log("Muscle keys CA:", Object.keys(musclesCa).length, "ES:", Object.keys(musclesEs).length, "EN:", Object.keys(musclesEn).length);

// Verify raw source exists (for rebuild capability)
const rawPath = "data/raw/free-exercise-db.json";
if (fs.existsSync(rawPath)) {
  const raw = require("./" + rawPath);
  console.log("Raw free-exercise-db exercises:", raw.length);
} else {
  console.warn("⚠️  Raw source not found at", rawPath);
}
